# Generated by Django 5.0.3 on 2024-03-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="memeber",
            new_name="member",
        ),
    ]
